name: Regression test (AMD64 GNU/Linux Clang, unity build)

on:
  push:
    branches: [main, rc]
  pull_request:
    branches: [main, rc]

jobs:
  test-with-clang:
    name: Test with Clang (unity build)
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        image:
          - url: ghcr.io/zhao-shihan/rgb-docker:mpich
            artifact-name: Regression test report (AMD64 GNU-Linux Clang, unity build, MPICH) 
          - url: ghcr.io/zhao-shihan/rgb-docker:openmpi
            artifact-name: Regression test report (AMD64 GNU-Linux Clang, unity build, OpenMPI) 
    container: ${{ matrix.image.url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS='-Werror -march=native' \
            -DCMAKE_CXX_FLAGS='-Werror -march=native' \
            -DMACE_FULL_UNITY_BUILD=ON
          ninja

      - name: Run regression test
        run: |
          . /environment
          bash build/test/regression_test.bash

      - name: Restore regression report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.artifact-name }}
          path: |
            build/test/test_*/regression_report.root
          retention-days: 90
