name: Regression test (AMD64 GNU/Linux GCC)

on:
  pull_request:
    branches:
      - main
      - rc
    paths:
      - ".github/workflows/regression-test-with-gcc.yml"
      - "src/**"
      - "test/**"
      - "MACE.c\\+\\+"
      - "**/CMakeLists.txt"
      - "**.cmake"

permissions:
  contents: read

jobs:
  regression-test-with-gcc:
    name: Regression test (GCC)
    timeout-minutes: 180
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - url: ghcr.io/zhao-shihan/rgb-docker:mpich
            artifact-name: Regression test report (AMD64 GNU-Linux GCC, MPICH)
          - url: ghcr.io/zhao-shihan/rgb-docker:openmpi
            artifact-name: Regression test report (AMD64 GNU-Linux GCC,OpenMPI)
    container: ${{ matrix.image.url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_C_FLAGS='-march=native' \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_CXX_FLAGS='-march=native'\
            -DMACESW_UNITY_BUILD=ON \
            -DMACESW_FULL_UNITY_BUILD=ON
          ninja

      - name: Run regression test
        run: |
          . /environment
          bash build/test/regression_test.bash --use-hwthreads

      - name: Restore regression report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.artifact-name }}
          path: |
            build/test/test_*/regression_report.root
          retention-days: 90
